### PR TITLE
Update projects.js

### PR DESCRIPTION
**Pull request by Trumilnasit**
updated router.post add some condiotion to check i think which is neccesary

### CODE REVIEW

**Comment by sanjay-kv** [comment]
https://github.com/Trumilnasit/Bitbox/pull/1

How can contributor add labels to the issue? who is the project admin of this @hemu21

**Comment by AKSHITHA-CHILUKA** [comment]
@sanjay-kv its actually forked repo so he added labels by himself in the pr

**Comment by hemanthkumar-21** [comment]
> https://github.com/Trumilnasit/Bitbox/pull/1
> 
> How can contributor add labels to the issue? who is the project admin of this @hemu21

Project admin of this project is harshit singh. @Harshit7492

**Comment by Anuj3553** [comment]
> > #1
> > How can contributor add labels to the issue? who is the project admin of this @Hemu21
> 
> Project admin of this project is harshit singh. @Harshit7492

Yes he is my friend, But he is inactive and the reason is I'm handled all the issues because i received a mail that we mark your into red flag project.

**Pull request merged**
